export const EMOJI = {
  notifications: '🔔',
  login: '🔑',
  signup: '✨',
  courses: '📚',
  explore: '🚀',
  profile: '👤',
  dashboard: '🗺️',
  warning: '⚠️',
  success: '✅',
  info: 'ℹ️',
  search: '🔎',
  book: '📖',
  message: '💬',
  calendar: '📅',
  privacy: '🔒',
  admin: '🛡️',
  rocket: '🚀',
  star: '⭐',
  wishlist: '❤️',
  cart: '🛒',
  instructor: '👨‍🏫',
  signout: '🚪'
};
export const emojiFor = (key) => EMOJI[key] ?? '🔹';
